#define ATTR_CUSED 0x2000
#define ATTR_CARRY 0x4000

struct opcode_data {
	uint32_t arg_add;
	uint8_t var;
	uint8_t reg;
	uint8_t arg1, arg2;
	uint8_t op;
	uint8_t carry;
	uint32_t opcode;
};

#define ARG_ADD_R0 ARG_ADD_REG
#define ARG_ADD_R1 ARG_ADD_REG
#define ARG_ADD_R2 ARG_ADD_REG
#define ARG_ADD_R3 ARG_ADD_REG
#define ARG_ADD_R4 ARG_ADD_REG
#define ARG_ADD_R5 ARG_ADD_REG
#define ARG_ADD_R6 ARG_ADD_REG
#define ARG_ADD_R7 ARG_ADD_REG

#define ARG_SUB_R0 ARG_SUB_REG
#define ARG_SUB_R1 ARG_SUB_REG
#define ARG_SUB_R2 ARG_SUB_REG
#define ARG_SUB_R3 ARG_SUB_REG
#define ARG_SUB_R4 ARG_SUB_REG
#define ARG_SUB_R5 ARG_SUB_REG
#define ARG_SUB_R6 ARG_SUB_REG
#define ARG_SUB_R7 ARG_SUB_REG

#define ARG_ADD_NR0 ARG_ADD_NREG
#define ARG_ADD_NR1 ARG_ADD_NREG
#define ARG_ADD_NR2 ARG_ADD_NREG
#define ARG_ADD_NR3 ARG_ADD_NREG
#define ARG_ADD_NR4 ARG_ADD_NREG
#define ARG_ADD_NR5 ARG_ADD_NREG
#define ARG_ADD_NR6 ARG_ADD_NREG
#define ARG_ADD_NR7 ARG_ADD_NREG

#define ARG_SUB_NR0 ARG_SUB_NREG
#define ARG_SUB_NR1 ARG_SUB_NREG
#define ARG_SUB_NR2 ARG_SUB_NREG
#define ARG_SUB_NR3 ARG_SUB_NREG
#define ARG_SUB_NR4 ARG_SUB_NREG
#define ARG_SUB_NR5 ARG_SUB_NREG
#define ARG_SUB_NR6 ARG_SUB_NREG
#define ARG_SUB_NR7 ARG_SUB_NREG

#define ALU_REG(_x) ALU_REG_##_x
#define ALU_REG_R0 REG_R0
#define ALU_REG_R1 REG_R1
#define ALU_REG_R2 REG_R2
#define ALU_REG_R3 REG_R3
#define ALU_REG_R4 REG_R4
#define ALU_REG_R5 REG_R5
#define ALU_REG_R6 REG_R6
#define ALU_REG_R7 REG_R7
#define ALU_REG_WR REG_NONE
#define ALU_REG_XWR REG_NONE
#define ALU_REG_DIP REG_NONE

#define ALU(_var, _a, _b, _x) \
	{ARG(ADD_NC), VAR_##_var, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0000|(_x)}, \
	{ARG(ADD_##_b)|ARG(SUB_##_a)|ARG(SUB_1)|ARG(ADD_C), VAR_##_var, ALU_REG(_a), 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0040|(_x)},\
	{ARG(ADD_##_a)|ARG(SUB_##_b)|ARG(SUB_1)|ARG(ADD_C), VAR_##_var, ALU_REG(_a), 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0100|(_x)},\
	{ARG(ADD_##_a)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, ALU_REG(_a), 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0140|(_x)},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0200|(_x)},\
	{ARG(ADD_N##_b)|ARG(ADD_C), VAR_##_var, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0240|(_x)},\
	{ARG(ADD_##_a)|ARG(ADD_C), VAR_##_var, ALU_REG(_a), 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0300|(_x)},\
	{ARG(ADD_N##_a)|ARG(ADD_C), VAR_##_var, ALU_REG(_a), 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, 0340|(_x)},\
	{0, VAR_##_var, 0, REG_##_a, REG_##_b, OP_AND, CARRY_UNUSED, 0400|(_x)},\
	{0, VAR_##_var, 0, REG_##_a, REG_##_b, OP_XOR, CARRY_UNUSED, 0440|(_x)},\
	{0, VAR_##_var, 0, REG_##_a, REG_##_b, OP_NXOR, CARRY_UNUSED, 0500|(_x)},\
	{0, VAR_##_var, 0, REG_N##_a, REG_##_b, OP_AND, CARRY_UNUSED, 0540|(_x)},\
	{0, VAR_##_var, 0, REG_##_a, REG_N##_b, OP_AND, CARRY_UNUSED, 0600|(_x)},\
	{0, VAR_##_var, 0, REG_##_a, REG_N##_b, OP_OR, CARRY_UNUSED, 0640|(_x)},\
	{0, VAR_##_var, 0, REG_N##_a, REG_##_b, OP_OR, CARRY_UNUSED, 0700|(_x)},\
	{0, VAR_##_var, 0, REG_##_a, REG_##_b, OP_OR, CARRY_UNUSED, 0740|(_x)}

#define SUM2_REG1(_var, _b, _op) \
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0000},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R1, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0001},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R2, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0002},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R3, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0003},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R4, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0004},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R5, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0005},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R6, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0006},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_R7, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0007}

#define SUM2(_var, _a, _b, _op) \
	{ARG(ADD_##_a)|ARG(ADD_##_b)|ARG(ADD_C), VAR_##_var, REG_##_a, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, _op}

#define SUM1(_var, _a, _op) \
	{ARG(ADD_##_a)|ARG(ADD_C), VAR_##_var, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, _op}

#define SUM2_VARREG_REG1(_b, _op) \
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R0, REG_R0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0000},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R1, REG_R1, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0001},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R2, REG_R2, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0002},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R3, REG_R3, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0003},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R4, REG_R4, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0004},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R5, REG_R5, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0005},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R6, REG_R6, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0006},\
	{ARG(ADD_REG)|ARG(ADD_##_b)|ARG(ADD_C), VAR_R7, REG_R7, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0007}

#define SUM1_VARREG(_b, _op) \
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R0, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0000},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R1, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0001},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R2, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0002},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R3, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0003},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R4, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0004},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R5, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0005},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R6, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0006},\
	{ARG(ADD_##_b)|ARG(ADD_C), VAR_R7, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0007}

#define SET_REG(_b, _op) \
	{ARG(ADD_##_b), VAR_R0, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0000},\
	{ARG(ADD_##_b), VAR_R1, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0001},\
	{ARG(ADD_##_b), VAR_R2, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0002},\
	{ARG(ADD_##_b), VAR_R3, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0003},\
	{ARG(ADD_##_b), VAR_R4, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0004},\
	{ARG(ADD_##_b), VAR_R5, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0005},\
	{ARG(ADD_##_b), VAR_R6, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0006},\
	{ARG(ADD_##_b), VAR_R7, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0007}

#define SET_TO_REG(_a, _op) \
	{ARG(ADD_REG), VAR_##_a, REG_R0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0000},\
	{ARG(ADD_REG), VAR_##_a, REG_R1, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0001},\
	{ARG(ADD_REG), VAR_##_a, REG_R2, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0002},\
	{ARG(ADD_REG), VAR_##_a, REG_R3, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0003},\
	{ARG(ADD_REG), VAR_##_a, REG_R4, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0004},\
	{ARG(ADD_REG), VAR_##_a, REG_R5, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0005},\
	{ARG(ADD_REG), VAR_##_a, REG_R6, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0006},\
	{ARG(ADD_REG), VAR_##_a, REG_R7, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, (_op)|0007}

#define SET(_var, _a, _op) \
	{ARG(ADD_##_a), VAR_##_var, 0, 0, 0, OP_ADD_SUB_NEG, CARRY_INDEFINITE, _op}

#define SHIFT(_op, _opcode) \
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_##_op, CARRY_UNUSED, _opcode}

#define SHIFT1_X(_op, _opcode) \
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP##_op##_X, CARRY_UNUSED, _opcode}

static const struct opcode_data _opcodes[] = {
	ALU(R0, R0, WR, 0),
	ALU(R1, R1, WR, 1),
	ALU(R2, R2, WR, 2),
	ALU(R3, R3, WR, 3),
	ALU(R4, R4, WR, 4),
	ALU(R5, R5, WR, 5),
	ALU(R6, R6, WR, 6),
	ALU(R7, R7, WR, 7),
	ALU(WR, R0, WR, 0010),
	ALU(WR, R1, WR, 0011),
	ALU(WR, R2, WR, 0012),
	ALU(WR, R3, WR, 0013),
	ALU(WR, R4, WR, 0014),
	ALU(WR, R5, WR, 0015),
	ALU(WR, R6, WR, 0016),
	ALU(WR, R7, WR, 0017),
	ALU(DOP, DIP, WR, 0030),
	ALU(WR, DIP, WR, 0031),
	ALU(WR, DIP, XWR, 0033),
	ALU(XWR, DIP, WR, 0034),
	ALU(XWR, DIP, XWR, 0036),
	ALU(DOP, DIP, XWR, 0037),
	SUM2_REG1(XWR, WR, 0160),
	SUM2_REG1(WR, DIP, 0220),
	SUM2_REG1(XWR, DIP, 0260),
	SUM2_VARREG_REG1(DIP, 0360),
	SUM2_REG1(WR, XWR, 0620),
	SUM2_REG1(XWR, XWR, 0660),
	SUM1_VARREG(XWR, 0720),
	SUM2(XWR, WR, DIP, 0172),
	SUM2(DOP, WR, DIP, 0372),
	SUM2(WR, XWR, DIP, 0632),
	SUM2(XWR, XWR, DIP, 0672),
	SUM1(DOP, XWR, 0732),
	SET_REG(DIP, 0760),
	SET_TO_REG(DOP, 0020),
	SET_REG(XWR, 0060),
	SET(WR, DIP, 0320),
	SET(XWR, DIP, 0072),
	SET(DOP, DIP, 0772),

	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_SAR, CARRY_INDEFINITE, 0035},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_ROR, CARRY_INDEFINITE, 0075},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_ROR, CARRY_INDEFINITE, 0475},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_SAL, CARRY_INDEFINITE, 0135},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_ROL, CARRY_INDEFINITE, 0175},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_ROL, CARRY_INDEFINITE, 0575},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_SHR, CARRY_INDEFINITE, 0435},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR, 0, 0, 0, OP_SHL, CARRY_INDEFINITE, 0535},

	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0235},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_ROR_X, CARRY_INDEFINITE, 0275},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_ROR_X, CARRY_INDEFINITE, 0675},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_SAL_X, CARRY_INDEFINITE, 0335},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0375},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0775},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_SHR_X, CARRY_INDEFINITE, 0635},
	{ARG(ADD_WR) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_SHL_X, CARRY_INDEFINITE, 0735},

	{ARG(ADD_WR) | ARG(SUB_DIP) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0432},
	{ARG(ADD_WR) | ARG(ADD_DIP) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0472},

	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R0, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0420},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R1, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0421},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R2, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0422},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R3, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0423},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R4, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0424},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R5, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0425},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R6, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0426},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R7, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0427},

	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R0, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0460},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R1, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0461},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R2, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0462},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R3, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0463},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R4, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0464},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R5, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0465},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R6, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0466},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R7, 0, 0, OP_ROL_X, CARRY_INDEFINITE, 0467},

	{ARG(ADD_WR) | ARG(SUB_DIP) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0132},
	{ARG(ADD_WR) | ARG(ADD_DIP) | ARG(ADD_C), VAR_WR_XWR, 0, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0572},

	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R0, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0120},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R1, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0121},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R2, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0122},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R3, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0123},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R4, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0124},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R5, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0125},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R6, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0126},
	{ARG(ADD_WR) | ARG(SUB_REG) | ARG(SUB_1) | ARG(ADD_C), VAR_WR_XWR, REG_R7, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0127},

	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R0, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0560},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R1, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0561},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R2, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0562},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R3, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0563},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R4, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0564},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R5, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0565},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R6, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0566},
	{ARG(ADD_WR) | ARG(ADD_REG) | ARG(ADD_C), VAR_WR_XWR, REG_R7, 0, 0, OP_SAR_X, CARRY_INDEFINITE, 0567},
	
	{0, 0, 0, 0, 0, OP_NOP, CARRY_UNUSED, NOP},
	{0, 0, 0, 0, 0, OP_HALT, CARRY_UNUSED, NOP},
	{0, 0, 0, 0, 0, 0, 0, 0},
};

